services:
  - type: web
    name: stroke-prediction-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      cd backend
      python3 -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
    startCommand: |
      cd backend
      bash start.sh

  - type: web
    name: stroke-prediction-frontend
    env: static
    region: oregon
    plan: free
    staticPublishPath: frontend
